on:
  push:
    branches:
    - master
  pull_request:
name: ci
jobs:
  linkage-monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: >
        mvn install -B -V \
         -Duser.home=/home/runner/work/_temp/_github_home \
         -DskipTests=true \
         -Dclirr.skip=true \
         -Denforcer.skip=true \
         -Dmaven.javadoc.skip=true \
         -Dgcloud.download.skip=true
    - uses: suztomo/cloud-opensource-java@v1
